Fix docker image tag and container volume path consistency in container build documentation
hacking-support/DVUEFI pull request #3
Opened 2024-08-13 22:49 UTC by cloudripper

This PR fixes minor typos in the documentation for setting up the build environment in docker container.

- The docker build command now uses the correct image tag `debian-qemu-uefi` to ensure consistency.
- Updated the `--volume` argument in the Docker command to correctly map the local `./vuln-edk2` directory to the appropriate directory inside the container - consistent with output displayed in the rest of the documentation.

These minor changes prevent potential confusion with setup of build environment.

2024-08-17 16:00 UTC, AkechiShiro commented
I tested this and do recommend this PR to be merged, as current documentation can be confusing indeed.

2024-08-28 15:39 UTC, staslyakhov requested changes
Hey, I just noticed this: thanks for noticing the inconsistencies and making a PR!

2024-08-28 15:39 UTC, staslyakhov commented on edk2-build-toolchain/README.md
> +docker build --tag debian-qemu-uefi edk2-build-toolchain
I think I would like to keep the name `dvuefi-build` here, as `debian-qemu-uefi` sounds misleading (at one point qemu was included in the image, but it isn't anymore).

Could we references to `debian-qemu-uefi` to be `dvuefi-build` instead?

2024-08-28 15:39 UTC, staslyakhov commented on edk2-build-toolchain/README.md
> +docker run --volume ./vuln-edk2:/home/vuln-edk2 --rm -it debian-qemu-uefi
:+1:

2024-09-05 15:20 UTC, staslyakhov approved these changes
Looks great, thanks!

2024-09-09 16:29 UTC, merged